############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

imports:
  - path: github.com/HugoBlox/kit/modules/integrations/netlify
  - path: github.com/HugoBlox/kit/modules/blox

# Install any Hugo Blox within the `hugo-blox/blox/` folder
mounts:
  - files:
      - '**.html'
    source: hugo-blox/blox/community
    target: layouts/partials/blox/community/
  - files:
      - '**.html'
    source: hugo-blox/blox/all-access
    target: layouts/partials/blox/
  - files:
      - '**.css'
    source: hugo-blox/blox
    target: assets/dist/community/blox/
  - source: layouts
    target: layouts
  - source: assets
    target: assets
