############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

imports:
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-decap-cms

# Install any Hugo Blox within the `hugo-blox/blox/` folder
mounts:
  - source: hugo-blox/blox/community
    target: layouts/partials/blox/community/
  - source: hugo-blox/blox/all-access
    target: layouts/partials/blox/
  - source: hugo-blox/blox
    target: assets/dist/community/blox/
  - source: layouts
    target: layouts
  - source: assets
    target: assets
